version: '3.8'

services:
    postgresql:
        image: postgres:14.5
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    postgres-data:
        driver: local
