version: '3.8'

services:
    postgresql_db:
        image: postgres:14.5
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: test_db
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: test@gmail.com
            PGADMIN_DEFAULT_PASSWORD: secret
        volumes:
            - pgadmin-data:/var/lib/pgadmin
volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local
